export type Article = {
    id: number
    title?: string
    img?: string
    category?: string[]
    tags?: string[]
    details?: {
        author: string
        date: {
            year: number
            monthNumber: number
            monthName: string
            day: number
        }
    }
    content?: {
        description: {
            firstParagraph: string
            subtitle: string
            secondParagraph: string
            quote: {
                text: string
                author: string
            }
        }
        general: {
            serves: number
            prepTime: string
            cookTime: string
            rating: {
                value: number
                votesNumber: number
                likes: number
            }
        }
        ingredients: string[]
        instructions: string[]
    }
}

const articlesArray: Article[] = [
    {
        id: 1,
        title: 'Creamy vegan pumpkin soup',
        img: '/images/recipes/p1.jpg',
        category: ['vegan'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.3,
                    votesNumber: 12,
                    likes: 11,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 2,
        title: 'Breakfast fried with bacon',
        img: '/images/recipes/p10.jpg',
        category: ['breakfast'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.5,
                    votesNumber: 4,
                    likes: 3,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 3,
        title: 'Classic apple pie recipe',
        img: '/images/recipes/p11.jpg',
        category: ['baking'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.5,
                    votesNumber: 6,
                    likes: 8,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 4,
        title: 'How to prepare breakfast platter',
        img: '/images/recipes/p13.jpg',
        category: ['breakfast'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.0,
                    votesNumber: 7,
                    likes: 8,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 5,
        title: 'Simple Nut & Fruit Puree Cup',
        img: '/images/recipes/p12.jpg',
        category: ['vegan'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 2,
                    likes: 5,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 6,
        title: 'Fresh Lime Detox Recipe',
        img: '/images/recipes/p14.jpg',
        category: ['drinks'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 3,
                    votesNumber: 2,
                    likes: 1,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 7,
        title: 'Simple Raisin Muffin Recipe',
        img: '/images/recipes/p15.jpg',
        category: ['baking'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.0,
                    votesNumber: 4,
                    likes: 3,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 8,
        title: 'Vegan Chocolate Cake Recipe',
        img: '/images/recipes/p16.jpg',
        category: ['vegan'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 3,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 9,
        title: 'Delicious Fresh Fruits Cake Recipe',
        img: '/images/recipes/p17.jpg',
        category: ['baking'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 3.5,
                    votesNumber: 4,
                    likes: 2,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 10,
        title: 'How To Prepare English Breakfast',
        img: '/images/recipes/p18.jpg',
        category: ['breakfast'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 11,
        title: 'Signatured Sangria Recipe',
        img: '/images/recipes/p19.jpg',
        category: ['drinks'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 2,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 12,
        title: 'Fresh Lychee Tea Recipe',
        img: '/images/recipes/p20.jpg',
        category: ['drinks'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 13,
        title: 'Simple Almond Cookie Recipe',
        img: '/images/recipes/p22.jpg',
        category: ['baking', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 3.5,
                    votesNumber: 4,
                    likes: 1,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 14,
        title: 'Green Breakfast Porridge Recipe',
        img: '/images/recipes/p4.jpg',
        category: ['breakfast', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 5,
                    likes: 2,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 15,
        title: 'Homemade Vegan Chocolate Recipe',
        img: '/images/recipes/p3.jpg',
        category: ['vegan', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.7,
                    votesNumber: 3,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 16,
        title: 'Avocado & Egg Simple Toast Recipe',
        img: '/images/recipes/p5.jpg',
        category: ['breakfast', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 4.5,
                    votesNumber: 2,
                    likes: 1,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 17,
        title: 'Rose Ice Cocktail Recipe',
        img: '/images/recipes/p6.jpg',
        category: ['drinks', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 18,
        title: 'Onion & Olive Sourdough Bread',
        img: '/images/recipes/p7.jpg',
        category: ['vegan', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 19,
        title: 'Simple Banan Muffin Recipe',
        img: '/images/recipes/p8.jpg',
        category: ['baking', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 1,
                    likes: 0,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
    {
        id: 20,
        title: 'Fruity Ice Blended Recipe',
        img: '/images/recipes/p9.jpg',
        category: ['drinks', 'featured'],
        tags:['food', 'recipe', 'soledad'],
        details: {
            author: 'Penci',
            date: {
                year: 2018,
                monthNumber: 8,
                monthName: 'August',
                day: 22,
            },
        },
        content: {
            description: {
                firstParagraph: 'Lommodo ligula eget dolor. Aenean massa. Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla onsequat massa quis enim. Donec pede justo fringilla vel aliquet nec vulputate eget. Lorem ispum dolore siamet ipsum dolor.',
                subtitle: 'Love what you do. Do what you love',
                secondParagraph: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.',
                quote: {
                    text: 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.',
                    author: 'Albert Camus',
                },
            },
            general: {
                serves: 4,
                prepTime: '15 minutes',
                cookTime: '25 minutes',
                rating: {
                    value: 5.0,
                    votesNumber: 2,
                    likes: 1,
                },
            },
            ingredients: [
                '2 1/2 cups (325g) all purpose flour',
                '2 cups (414g) sugar',
                '3 tsp baking powder',
                '1 tsp salt',
                '1 cup (240ml) milk',
                '1/2 cup (120ml) vegetable oil',
                '1 tbsp vanilla extract',
                '2 large eggs',
                '1 cup (240ml) water',
                '1 1/2 cup (240g) mixed berries (I used strawberries, blueberries and raspberries)',
                '3 tbsp (45ml) water',
                '3/4 cup (155g) sugar',
                '3 tbsp cornstarch',
            ],
            instructions: [
                'Preheat oven to 350°F (176°C) and prepare three 8 inch cake pans with non-stick baking spray and parchment paper in the bottom. These cakes can have a tendency to stick to the pans a bit, so I strongly recommend the parchment paper in the bottom.',
                'Add the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside.',
                'Add the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine.',
                'Add the wet ingredients to the dry ingredients and beat until well combined.',
                'Slowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.',
                'Divide the batter evenly between the prepared cake pans and bake for 24-28 minutes, or until a toothpick comes out with a few moist crumbs.',
                'Remove the cakes from oven and allow to cool for 2-3 minutes, then remove to a cooling rack to finish cooling. These cakes can have a tendency to stick to the pans a bit so jiggle them a bit to loosen from the sides of the pan before turning the cakes out to cool.',
            ],
        },
    },
]

export const getArticlesObject = (array: Article[]) =>
    array.reduce((object, article) => ({
    ...object,
    [article.id]: article,
    }), {})

export const articlesObject: {[id: number]: Article} = getArticlesObject (articlesArray)

export default articlesArray